import subprocess
import os
import sys
import yaml
import datetime

def run_command(command, step_name):
    """Helper to run shell commands and handle errors"""
    print(f"\n{'='*50}")
    print(f"🚀 STARTING: {step_name}")
    print(f"{'='*50}\n")
    try:
        # Run the command and wait for it to finish. 
        # check=True raises CalledProcessError if it fails.
        subprocess.run(command, check=True, shell=True)
        print(f"\n✅ COMPLETED: {step_name}")
    except subprocess.CalledProcessError as e:
        print(f"\n❌ FAILED: {step_name}")
        print(f"Error details: {e}")
        sys.exit(1)

def generate_report():
    """Reads config and results to generate a Markdown report"""
    print("\n📝 Generating REPORT.md...")
    
    # Load all necessary data
    with open('config.yaml', 'r') as f:
        config = yaml.safe_load(f)
    
    if not os.path.exists('results.yaml'):
        print("❌ Error: results.yaml not found. Did training fail?")
        return

    with open('results.yaml', 'r') as f:
        results = yaml.safe_load(f)

    # Create the Markdown content
    md_content = f"""# 🎵 Emotitune Experiment Report
**Date:** {datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

## 📊 Summary of Results
| Metric | Value |
| :--- | :--- |
| **Best Validation Loss** | `{results['best_val_loss']:.4f}` |
| **Final Accuracy** | `{results['final_accuracy']*100:.2f}%` |
| **Weighted F1-Score** | `{results['final_f1_score']:.4f}` |

## ⚙️ Configuration Used
* **Epochs:** {config['training']['num_epochs']} (Patience: {config['training']['patience']})
* **Batch Size:** {config['training']['batch_size']}
* **Learning Rate:** {config['training']['learning_rate']}
* **Audio Features:** MFCC({config['audio']['n_mfcc']}), Chroma, Spectral Contrast, Tonnetz

## 🧩 Confusion Matrix
Visualizes which emotions the model confuses with each other.
![Confusion Matrix](confusion_matrix.png)

---
*Report automatically generated by `run.py`*
"""

    # Write the file
    with open('REPORT.md', 'w') as f:
        f.write(md_content)
    
    print("✨ REPORT.md created successfully!")

def main():
    # 1. Run Feature Extraction
    # We use sys.executable to ensure we use the same python env that ran run.py
    python_executable = sys.executable
    run_command(f"{python_executable} src/audio/save_features.py", "Feature Extraction")

    # 2. Run Training
    run_command(f"{python_executable} src/audio/cnn_baseline.py", "Model Training")

    # 3. Generate Report
    generate_report()

    print("\n🎉 PIPELINE FINISHED! Check REPORT.md for details.")

if __name__ == "__main__":
    main()